// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package cc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DdClient is the client API for Dd service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DdClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type ddClient struct {
	cc grpc.ClientConnInterface
}

func NewDdClient(cc grpc.ClientConnInterface) DdClient {
	return &ddClient{cc}
}

func (c *ddClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/bb.cc.Dd/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DdServer is the server API for Dd service.
// All implementations must embed UnimplementedDdServer
// for forward compatibility
type DdServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedDdServer()
}

// UnimplementedDdServer must be embedded to have forward compatible implementations.
type UnimplementedDdServer struct {
}

func (UnimplementedDdServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedDdServer) mustEmbedUnimplementedDdServer() {}

// UnsafeDdServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DdServer will
// result in compilation errors.
type UnsafeDdServer interface {
	mustEmbedUnimplementedDdServer()
}

func RegisterDdServer(s grpc.ServiceRegistrar, srv DdServer) {
	s.RegisterService(&Dd_ServiceDesc, srv)
}

func _Dd_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bb.cc.Dd/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Dd_ServiceDesc is the grpc.ServiceDesc for Dd service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Dd_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bb.cc.Dd",
	HandlerType: (*DdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Dd_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Dd.proto",
}
